# Generated by Django 5.0.6 on 2026-08-16 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFrequencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('percentual_presenca', models.FloatField()),
                ('total_marcacoes', models.IntegerField()),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_frequencia', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Relatório de Frequência',
                'verbose_name_plural': 'Relatórios de Frequência',
                'db_table': 'relatorios_frequencia',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
