# Generated by Django 5.0.6 on 2026-08-16 22:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=255)),
                ('numero_art', models.CharField(blank=True, help_text='Anotação de Responsabilidade Técnica (CREA) ou Registro de Responsabilidade Técnica (CAU) da obra -- não é preciso CNPJ pra cadastrar. Obrigatória por lei (6.496/77) antes do início da obra, mas deixamos opcional aqui pra não travar o cadastro de obras já em andamento sem o número à mão ainda.', max_length=30, verbose_name='Número da ART/RRT')),
                ('latitude_centro', models.FloatField()),
                ('longitude_centro', models.FloatField()),
                ('raio_metros', models.FloatField(default=5.0)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obras',
                'ordering': ['nome'],
            },
        ),
    ]
