# Generated by Django 5.0.6 on 2026-08-16 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='dono',
            field=models.ForeignKey(limit_choices_to={'papel': 'DONO'}, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obra',
            name='gerente',
            field=models.OneToOneField(blank=True, limit_choices_to={'papel': 'GERENTE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obra_gerenciada', to=settings.AUTH_USER_MODEL),
        ),
    ]
