# Generated by Django 5.0.6 on 2026-08-30 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='gerente',
        ),
        migrations.CreateModel(
            name='VinculoGerente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('especialidade', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('gerente', models.ForeignKey(limit_choices_to={'papel': 'GERENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_obra', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_gerente', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Vínculo de Gerente',
                'verbose_name_plural': 'Vínculos de Gerente',
                'db_table': 'vinculos_gerente',
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='gerentes',
            field=models.ManyToManyField(blank=True, related_name='obras_gerenciadas', through='obras.VinculoGerente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vinculogerente',
            constraint=models.UniqueConstraint(fields=('obra', 'gerente', 'especialidade'), name='vinculo_gerente_unico'),
        ),
    ]
