# Generated by Django 5.0.6 on 2026-09-08 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='raio_metros',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(5.0)]),
        ),
    ]
