# Generated by Django 5.0.6 on 2026-08-16 22:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiometriaFacial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vetor_criptografado', models.TextField(help_text='Vetor facial cifrado -- nunca a imagem crua (RS02/LGPD).')),
                ('algoritmo', models.CharField(default='aws-rekognition', max_length=50)),
                ('qualidade_amostra', models.FloatField()),
                ('capturado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Biometria Facial',
                'verbose_name_plural': 'Biometrias Faciais',
                'db_table': 'biometrias_faciais',
            },
        ),
    ]
