# Generated by Django 5.0.6 on 2026-08-16 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biometria', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometriafacial',
            name='operario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometria', to='usuarios.perfiloperario'),
        ),
    ]
