# Generated by Django 5.0.6 on 2026-08-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometriafacial',
            name='algoritmo',
            field=models.CharField(default='sdk-dispositivo', help_text='Identifica o SDK que extraiu o vetor no aparelho (ex.: ML Kit, MediaPipe) -- não é mais processado no backend.', max_length=50),
        ),
    ]
