# Generated by Django 5.0.6 on 2026-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometria', '0003_alter_biometriafacial_algoritmo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometriafacial',
            name='algoritmo',
            field=models.CharField(default='mobilefacenet-tflite-v1', help_text='Identifica o modelo que gerou o embedding no aparelho (ex.: mobilefacenet-tflite-v1, via react-native-fast-tflite). Nunca compare vetores de algoritmos diferentes -- espaços vetoriais incompatíveis (ver biometria/services.py).', max_length=50),
        ),
    ]
