# Generated by Django 5.0.6 on 2026-08-16 22:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_hash', models.CharField(max_length=64)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('imutavel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'logs_auditoria',
            },
        ),
        migrations.CreateModel(
            name='SessaoOffline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispositivo_id', models.CharField(max_length=100)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('sincronizada_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('SINCRONIZADO', 'Sincronizado'), ('FALHA', 'Falha')], default='PENDENTE', max_length=15)),
            ],
            options={
                'verbose_name': 'Sessão Offline',
                'verbose_name_plural': 'Sessões Offline',
                'db_table': 'sessoes_offline',
            },
        ),
        migrations.CreateModel(
            name='MarcacaoPonto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nsr', models.CharField(editable=False, help_text='Exigido pelo AFD da Portaria 671/MTE.', max_length=20, unique=True, verbose_name='Número Sequencial de Registro')),
                ('data_hora', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('precisao_gps_metros', models.FloatField()),
                ('confianca_face', models.FloatField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('INTERVALO_INICIO', 'Início do intervalo'), ('INTERVALO_FIM', 'Fim do intervalo')], max_length=20)),
                ('origem', models.CharField(choices=[('APP_OPERARIO', 'App do operário'), ('CONTINGENCIA_GERENTE', 'Contingência (gerente)'), ('SYNC_OFFLINE', 'Sincronização offline')], default='APP_OPERARIO', max_length=25)),
                ('sincronizado', models.BooleanField(default=True)),
                ('hash_integridade', models.CharField(editable=False, max_length=64)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='obras.obra')),
            ],
            options={
                'verbose_name': 'Marcação de Ponto',
                'verbose_name_plural': 'Marcações de Ponto',
                'db_table': 'marcacoes_ponto',
                'ordering': ['-data_hora'],
            },
        ),
    ]
