# Generated by Django 5.0.6 on 2026-08-16 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponto', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacaoponto',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes', to='usuarios.perfiloperario'),
        ),
        migrations.AddField(
            model_name='marcacaoponto',
            name='registrado_por',
            field=models.ForeignKey(help_text='Normalmente o próprio operário; em contingência (UC07), o gerente.', on_delete=django.db.models.deletion.PROTECT, related_name='marcacoes_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='marcacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='log_auditoria', to='ponto.marcacaoponto'),
        ),
        migrations.AddField(
            model_name='marcacaoponto',
            name='sessao_offline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcacoes', to='ponto.sessaooffline'),
        ),
        migrations.AddIndex(
            model_name='marcacaoponto',
            index=models.Index(fields=['operario', 'data_hora'], name='marcacoes_p_operari_2d40d6_idx'),
        ),
        migrations.AddIndex(
            model_name='marcacaoponto',
            index=models.Index(fields=['obra', 'data_hora'], name='marcacoes_p_obra_id_8225cc_idx'),
        ),
    ]
