# Generated by Django 5.0.6 on 2026-08-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacaoponto',
            name='dispositivo_id',
            field=models.CharField(blank=True, max_length=150, verbose_name='ID do dispositivo'),
        ),
        migrations.AddField(
            model_name='marcacaoponto',
            name='sistema_operacional',
            field=models.CharField(blank=True, max_length=100, verbose_name='sistema operacional'),
        ),
        migrations.AlterField(
            model_name='marcacaoponto',
            name='origem',
            field=models.CharField(choices=[('APP_OPERARIO', 'App do operário'), ('CONTINGENCIA_GERENTE', 'Contingência (gerente, digital)'), ('CONTINGENCIA_PAPEL', 'Contingência em papel (aprovada depois)'), ('SYNC_OFFLINE', 'Sincronização offline')], default='APP_OPERARIO', max_length=25),
        ),
    ]
