# Generated by Django 5.0.6 on 2026-08-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiloperario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfiloperario',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
