# Generated by Django 5.0.6 on 2026-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfis_vinculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilgerente',
            name='tipo_gerente',
            field=models.CharField(blank=True, choices=[('OBRA', 'Gerente de Obra'), ('CIVIL_ESTRUTURAL', 'Gerente Civil/Estrutural'), ('ELETRICA', 'Gerente Elétrico'), ('HIDRAULICA', 'Gerente Hidráulico/Sanitário'), ('SEGURANCA_TRABALHO', 'Gerente de Segurança do Trabalho'), ('QUALIDADE', 'Gerente de Qualidade'), ('PLANEJAMENTO', 'Gerente de Planejamento e Controle'), ('SUPRIMENTOS', 'Gerente de Suprimentos/Compras'), ('MANUTENCAO', 'Gerente de Manutenção/Equipamentos'), ('AMBIENTAL', 'Gerente Ambiental'), ('FINANCEIRO', 'Gerente Financeiro'), ('RECURSOS_HUMANOS', 'Gerente de Recursos Humanos'), ('COMERCIAL', 'Gerente Comercial'), ('GERAL', 'Gerente Geral'), ('OUTRO', 'Outro')], help_text='Especialidade padrão do gerente (pode variar por obra -- ver VinculoGerente.especialidade).', max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('DONO', 'Dono'), ('GERENTE', 'Gerente'), ('OPERARIO', 'Operário'), ('ADMIN', 'Administrador')], max_length=10),
        ),
    ]
